config/routes.rb
Rails.application.routes.draw do

  root to: 'users#home'
  get '/api/undetermined' => 'api/predictions#undetermined'
  get '/undetermined' => 'predictions#undetermined'
  post '/judgments' => 'judgments#create'

  resource :session, only: [:create, :destroy, :new]

  resources :users, only: [:create, :new, :show]
  resources :predictions, only: [:index, :new, :create, :show]
  resources :wagers, only: [:create]

  namespace :api, defaults: { format: :json } do
    resources :predictions, only: [:index, :show]
    resources :wagers, only: [:index]
    resources :judgments, only: [:index]
    resources :quotes, only: [:index]
  end
end

app/models/prediction.rb
# == Schema Information
#
# Table name: predictions
#
#  id         :integer          not null, primary key
#  user_id    :integer          not null
#  statement  :string(255)      not null
#  deadline   :datetime         not null
#  created_at :datetime
#  updated_at :datetime
#  judged     :boolean          default(FALSE)
#

class Prediction < ActiveRecord::Base
  validates :statement, :deadline, presence: true
  validates :statement, length: { in: (1..140) }
  validates :statement, uniqueness: true
  # validate :date_must_be_in_future
  belongs_to(:user)
  has_many(:wagers)
  has_many(:judgments)

  def self.parse_datetime(string)
    Chronic.parse(string)
  end

  def self.due_for_judgment_count
    Prediction.due_for_judgment.count
  end

  def self.due_for_judgment
    Prediction.where('judged = ? AND deadline < ?', false, Time.now)
  end

  def average_wager
    sum = 0

    wagers.each do |wager|
      sum += wager.probability
    end

    (sum.to_f / wagers.length).round
  end

  private

  # def date_must_be_in_future
  #   return if self.deadline.nil?
  #
  #   if self.deadline < Time.now
  #     errors.add(:deadline, "must be in the future... this isn't RetrodictionNote")
  #   end
  # end
end

app/controllers/api/predictions_controller.rb
module Api
  class PredictionsController < ApplicationController
    def index
      @predictions = Prediction.all
      render json: @predictions
    end

    def undetermined
      @due_for_judgment = Prediction.due_for_judgment
      render json: @due_for_judgment
    end

    def show
      @prediction = Prediction.find(params[:id])
      render json: @prediction
    end
  end
end

app/controllers/predictions_controller.rb
class PredictionsController < ApplicationController
  before_action :require_signed_in!, only: [:new, :create]

  def index
    @predictions = Prediction.last(50).reverse
    render :index
  end

  def undetermined
    @due_for_judgment = Prediction.due_for_judgment.sort_by(&:deadline)
    render :undetermined
  end

  def tutorial
    render :tutorial
  end

  def new
    render :new
  end

  def create
    @prediction = Prediction.new
    @prediction.statement = params[:prediction][:statement]
    @prediction.deadline = Prediction.parse_datetime(params[:prediction][:deadline])
    @prediction.user_id = current_user.id

    if @prediction.save
      redirect_to prediction_url(@prediction)
    else
      flash.now[:errors] = @prediction.errors.full_messages
      render :new
    end
  end

  def show
    @prediction = Prediction.find(params[:id])
    @judgment = @prediction.judgments.last
    render :show
  end
end

app/helpers/predictions_helper.rb
module PredictionsHelper
end

app/views/predictions/index.html.erb
<h1>Predictions</h1>
<table class="table table-striped table-hover ">
  <thead>
    <tr>
      <th>#</th>
      <th id="prediction-statement-column">Statement</th>
      <th id="average-probability-column">Average Probability</th>
      <th id="deadline-column">Deadline</th>
    </tr>
  </thead>
  <tbody>
    <% count = 0 %>

    <% @predictions.each do |prediction| %>
    <% count += 1 %>
      <tr>
        <td><%= count %></td>

        <td>
          <% judgment = prediction.judgments.last %>
          <% if judgment && judgment.status == "verified" %>
            <span class="text-success">✔</span>
          <% elsif judgment && judgment.status == "falsified" %>
            <span class="text-danger">❌</span>
          <% else %>
            <span class="text-info">⚫</span>
          <% end %>
          <%= link_to(prediction.statement, prediction_url(prediction)) %>

        </td>

        <% if prediction.wagers.empty? %>
          <td>N/A</td>
        <% else %>
          <td><%= prediction.average_wager %>%</td>
        <% end %>

        <% if prediction.deadline < Time.now %>
          <td><%= distance_of_time_in_words(prediction.deadline, Time.now) %> ago</td>
        <% else %>
          <td>in <%= distance_of_time_in_words(prediction.deadline, Time.now) %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<script>
var localTour;

localTour = new Shepherd.Tour({
  defaults: {
    classes: 'shepherd-theme-arrows',
    scrollTo: true
  }
});

localTour.addStep('overview-step', {
  title: "<strong>Predictions Tutorial</strong>",
  text: "The predictions page consists of a list of the 50 most recent predictions.",
  classes: 'shepherd-theme-arrows',
  buttons: [
  {
    text: 'Exit',
    action: localTour.cancel
  },
  {
    text: 'Next',
    action: localTour.next
  }
  ]
});

localTour.addStep('statement-step', {
  title: "<strong>Predictions Tutorial</strong>",
  text: "<p>The statement column of the table contains the prediction statements and are marked with symbols disignating their judgment-status.</p>" +
  "<p class='text-info'>⚫: Undetermined</p>" +
  "<p class='text-success'>✔: Verified</p>" +
  "<p class='text-danger'>❌: Falsified</p>",
  classes: 'shepherd-theme-arrows',
  scrollTo: false,
  attachTo: "#prediction-statement-column bottom",
  buttons: [
  {
    text: 'Back',
    action: localTour.back
  },
  {
    text: 'Next',
    action: localTour.next
  }
  ]
});

localTour.addStep('average-probability-step', {
  title: "<strong>Predictions Tutorial</strong>",
  text: "<p>The average probabilty column respresents the sum of the wagers made on that prediction " +
  "divided by the total number of users that made wagers.</p> " +
  "<p>This should give you an idea about how likely other users believe the prediction to be.</p>",
  classes: 'shepherd-theme-arrows',
  scrollTo: false,
  attachTo: "#average-probability-column bottom",
  buttons: [
  {
    text: 'Back',
    action: localTour.back
  },
  {
    text: 'Next',
    action: localTour.next
  }
  ]
});

localTour.addStep('deadline-step', {
  title: "<strong>Predictions Tutorial</strong>",
  text: "The deadline column respresents the 'due date' of that prediction. " +
  "If it is in the past tense, then the truth-value of the statement should already be known. " +
  "Otherwise, there is still time left in which it may occur.",
  classes: 'shepherd-theme-arrows',
  scrollTo: false,
  attachTo: "#deadline-column bottom",
  buttons: [
  {
    text: 'Back',
    action: localTour.back
  },
  {
    text: 'Next',
    action: localTour.next
  }
  ]
});

localTour.addStep('visit-step', {
  title: "<strong>Predictions Tutorial</strong>",
  text: "Click on a predictions statement in order to learn more about that prediction.",
  classes: 'shepherd-theme-arrows',
  buttons: [
  {
    text: 'Back',
    action: localTour.back
  },
  {
    text: 'End',
    action: localTour.next
  }
  ]
});

$(document).ready(function () {
  $('#tutorial-button').on('click', function (event) {
    event.preventDefault();
    localTour.start();
  });
});
</script>

app/views/predictions/new.html.erb
<form class="form-horizontal" action="<%= predictions_url %>" method="post">

  <input type="hidden"
  name="authenticity_token"
  value="<%= form_authenticity_token %>">

  <fieldset>
    <legend><h1>Make a New Prediction</h1></legend>
    <div class="form-group" style="width: 50%;">
      <label for="inputStatement" class="col-lg-2 control-label">Statement</label>
      <div class="col-lg-10">
        <input type="text"
               class="form-control"
               id="inputStatement"
               name="prediction[statement]"
               placeholder="Godzilla will attack Tokyo within the week.">
      </div>
    </div>
    <div class="form-group" style="width: 50%;">
      <label for="inputDeadline" class="col-lg-2 control-label">Deadline</label>
      <div class="col-lg-10">
        <input type="datetime"
               class="form-control"
               id="inputDeadline"
               name="prediction[deadline]"
               placeholder="in seven days">
      </div>
    </div>

    <div class="form-group" style="width: 50%;">
      <div class="col-lg-10 col-lg-offset-2">
        <button id="new-prediction-submit-button"type="submit" class="btn btn-primary">Submit</button>
      </div>
    </div>
  </fieldset>
</form>

<script>
var localTour;

localTour = new Shepherd.Tour({
  defaults: {
    classes: 'shepherd-theme-arrows',
    scrollTo: true
  }
});

localTour.addStep('overview-step', {
  title: "<strong>New Prediction Tutorial</strong>",
  text: "The new prediction page provides a form for you to make your own prediction.",
  classes: 'shepherd-theme-arrows',
  buttons: [
  {
    text: 'Exit',
    action: localTour.cancel
  },
  {
    text: 'Next',
    action: localTour.next
  }
  ]
});

localTour.addStep('statement-step', {
  title: "<strong>New Prediction Tutorial</strong>",
  text: "<p>Enter your own prediction here.</p>" +
  "<p>You aren't allowed to judge your own predictions, " +
  "so make sure your proposition will be easy to score given publicly available information.</p>" +
  "<p><span class='text-info'><strong>Good: Hilary Clinton will be elected POTUS in 2016.</strong></span></p>" +
  "<p><span class='text-warning'><strong>Bad: Invisible gnomes will steal my keys before the heat death of the universe.</strong></span></p>",
  classes: 'shepherd-theme-arrows',
  attachTo: "#inputStatement right",
  buttons: [
  {
    text: 'Back',
    action: localTour.back
  },
  {
    text: 'Next',
    action: localTour.next
  }
  ]
});

localTour.addStep('deadline-step', {
  title: "<strong>New Prediction Tutorial</strong>",
  text: "Enter your deadline here." +
  "You can enter deadlines in a <strong>YYYY/MM/DD</strong> format, " +
  "like <strong>'2016-12-01'</strong>, or even in plain English, " +
  "such as <strong>'in two weeks'</strong>, " +
  "or <strong>'in seven years'</strong>.",
  classes: 'shepherd-theme-arrows',
  attachTo: "#inputDeadline right",
  buttons: [
  {
    text: 'Back',
    action: localTour.back
  },
  {
    text: 'Next',
    action: localTour.next
  }
  ]
});

localTour.addStep('submit-step', {
  title: "<strong>New Prediction Tutorial</strong>",
  text: "Don't forget to click <strong>Submit</strong> when you are finished. " +
  "If you make a mistake, a warning will appear above the form to let you know what went wrong.",
  classes: 'shepherd-theme-arrows',
  attachTo: "#new-prediction-submit-button bottom",
  buttons: [
  {
    text: 'Back',
    action: localTour.back
  },
  {
    text: 'End',
    action: localTour.next
  }
  ]
});

$(document).ready(function() {
  $('#tutorial-button').on('click', function (event) {
    event.preventDefault();
    localTour.start();
  });
});
</script>

app/views/predictions/show.html.erb
<% unless signed_in? %>
  <div class="panel panel-info">
    <div class="panel-heading">
      <h3 class="panel-title">Login Reminder</h3>
    </div>
    <div class="panel-body">
      You must be logged in to create a new prediction, place a wager, or to make a judgment.
    </div>
  </div>
<% end %>

<div>

  <% if @judgment && @judgment.status == "verified" %>
    <h3 id="statement" data-prediction-id="<%= @prediction.id %>" class="text-success">
  <% elsif @judgment && @judgment.status == "falsified" %>
    <h3 id="statement" data-prediction-id="<%= @prediction.id %>" class="text-danger">
  <% else %>
    <h3 id="statement" data-prediction-id="<%= @prediction.id %>" class="text-info">
  <% end %>
      <strong><em><%= @prediction.statement %></em></strong>
    </h3>
  <h5><em><strong>Created at</strong>: <%= @prediction.created_at %><% if @judgment then %>, <strong>Judged at</strong>: <%= @judgment.created_at %><% end %></em></h5>
  <h5>
  <% if @prediction.deadline < Time.now %>
    The outcome was known
    <%= distance_of_time_in_words(@prediction.deadline, Time.now) %> ago.
  <% else %>
    The outcome will be known in
    <%= distance_of_time_in_words(@prediction.deadline, Time.now) %>.
  <% end %>
</h5>


  <h6><strong>Predictor</strong>: <%= link_to(@prediction.user.username, @prediction.user) %><% if @judgment then %>, <strong>Judge</strong>: <%= link_to(@judgment.user.username, @judgment.user) %><% end %></h6>
</div>

<% unless @prediction.wagers.empty? %>
  <br>
  <% average = @prediction.average_wager %>

  <h4>Average Probability</h4>
  <% if average < 33 %>
    <div class="progress">
      <div class="progress-bar progress-bar-danger" style="width: <%= average %>%"><%= average %>%</div>
    </div>
  <% elsif average > 66 %>
    <div class="progress">
      <div class="progress-bar progress-bar-success" style="width: <%= average %>%"><%= average %>%</div>
    </div>
  <% else %>
    <div class="progress">
      <div class="progress-bar progress-bar-info" style="width: <%= average %>%"><%= average %>%</div>
    </div>
  <% end %>

  <div>
    <h4>Wagers</h4>
    <ul>
    <% @prediction.wagers.each do |wager| %>
      <li>
        <%= wager.probability %>% <%= link_to(wager.user.username, wager.user) %>
        on <%= wager.created_at %>
      </li>
    <% end %>
    </ul>
  </div>

  <br>
<% end %>

<% if @prediction.deadline > Time.now && signed_in? %>
  <div class="form-group">
    <h4>Make a Wager</h4>
    <div class="well">
      <form action="<%= wagers_url %>" method="post">

        <input type="hidden"
        name="authenticity_token"
        value="<%= form_authenticity_token %>">

        <input type="hidden"
        name="wager[prediction_id]"
        value="<%= @prediction.id %>">

        <label>
          Probability (0-100%)
          <input type="number"
                name="wager[probability]"
                class="form-control"
                value="50"
                min="0"
                max="100">
        </label>
        <br>

        <input type="submit" value="Affirm!" class="btn-default">
      </form>
    </div>
  </div>
<% end %>

<% if signed_in? && current_user.id != @prediction.user_id %>
  <div class="form-group">
    <h4>Make a Judgment</h4>
    <div class="well">
      <div class="btn-group btn-group-justified">
        <a href="#"
           class="btn btn-success"
           data-status="verified"
           data-toggle="tooltip"
           data-placement="bottom"
           data-original-title="Click here only if you have made sure this prediction was true.">Verified</a>
        <a href="#"
           class="btn btn-info"
           data-status="undetermined"
           data-toggle="tooltip"
           data-placement="bottom"
           data-original-title="Click here only if you the previous judgment was incorrect." >Undetermined</a>
        <a href="#"
           class="btn btn-danger"
           data-status="falsified"
           data-toggle="tooltip"
           data-placement="bottom"
           data-original-title="Click here only if you have made sure this prediction was false.">Falsified</a>


      </div>
    </div>
  </div>
<% end %>

<script>
// activate tooltip
$(function () {
  $("[data-toggle='tooltip']").tooltip({container: 'body'});
});

$(document).ready(function () {
  $(".btn-success").on("click", function() {
    $.ajax({
      type: "POST",
      url: '/judgments.json',
      data: {
        "prediction_id": $('#statement').data('prediction-id'),
        "status": "verified"},
      success: function () {
        $('#statement').removeClass('text-info');
        $('#statement').removeClass('text-danger');
        $('#statement').addClass('text-success');
        var count = Number($('.badge').html()) - 1;
        $('.badge').html(count);
      },
      error: function () {
        alert("The judgment failed!")
      },
      dataType: 'JSON'
    });
  });

  $(".btn-info").on("click", function() {
    $.ajax({
      type: "POST",
      url: '/judgments.json',
      data: {
        "prediction_id": $('#statement').data('prediction-id'),
        "status": "undetermined"},
        success: function () {
          $('#statement').addClass('text-info');
          $('#statement').removeClass('text-danger');
          $('#statement').removeClass('text-success');
          var count = Number($('.badge').html()) + 1;
          $('.badge').html(count);
        },
        error: function () {
          alert("The judgment failed!")
        },
        dataType: 'JSON'
      });
    });

    $(".btn-danger").on("click", function() {
      $.ajax({
        type: "POST",
        url: '/judgments.json',
        data: {
          "prediction_id": $('#statement').data('prediction-id'),
          "status": "falsified"},
          success: function () {
            $('#statement').removeClass('text-info');
            $('#statement').addClass('text-danger');
            $('#statement').removeClass('text-success');
            var count = Number($('.badge').html()) - 1;
            $('.badge').html(count);
          },
          error: function () {
            alert("The judgment failed!")
          },
          dataType: 'JSON'
        });
      });
});
</script>

app/views/predictions/undetermined.html.erb
<h1>Overdue Predictions</h1>
<table class="table table-striped table-hover ">
  <thead>
    <tr>
      <th>#</th>
      <th>Statement</th>
      <th>Deadline</th>
    </tr>
  </thead>
  <tbody>
    <% count = 0 %>

    <% @due_for_judgment.each do |prediction| %>
      <% count += 1 %>
      <tr>
        <td><%= count %></td>
        <td>
          <span class="text-info">⚫</span>
          <%= link_to(prediction.statement, prediction_url(prediction)) %>
        </td>
        <td><%= distance_of_time_in_words(prediction.deadline, Time.now) %> ago</td>
      </tr>
    <% end %>
  </tbody>
</table>

<script>
var localTour;

localTour = new Shepherd.Tour({
  defaults: {
    classes: 'shepherd-theme-arrows',
    scrollTo: true
  }
});

localTour.addStep('overview-step', {
  title: "<strong>Overdue Predictions Tutorial</strong>",
  text: "<p>The overdue predictions page lists all the predictions that need to be judged.</p>" +
  "<p>Click on a statement if you want to judge it or learn more about it (such as which users have placed wagers on it). " +
  "Just remember, if you were the original creator of the prediction, you will not be permitted to judge it yourself.</p>",
  classes: 'shepherd-theme-arrows',
  buttons: [
  {
    text: 'End',
    action: localTour.next
  }
  ]
});

$(document).ready(function() {
  $('#tutorial-button').on('click', function (event) {
    event.preventDefault();
    localTour.start();
  });
});
</script>