config/routes.rb
Rails.application.routes.draw do

  root to: 'users#home'
  get '/api/undetermined' => 'api/predictions#undetermined'
  get '/undetermined' => 'predictions#undetermined'
  post '/judgments' => 'judgments#create'

  resource :session, only: [:create, :destroy, :new]

  resources :users, only: [:create, :new, :show]
  resources :predictions, only: [:index, :new, :create, :show]
  resources :wagers, only: [:create]

  namespace :api, defaults: { format: :json } do
    resources :predictions, only: [:index, :show]
    resources :wagers, only: [:index]
    resources :judgments, only: [:index]
    resources :quotes, only: [:index]
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PredictionNote</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<header>
  <div class="navbar navbar-default">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a id="home-page-button" class="navbar-brand" href="<%= root_url %>"><strong>PredictionNote</strong></a>
    </div>
    <div class="navbar-collapse collapse navbar-responsive-collapse">
      <ul class="nav navbar-nav">
        <li id="predictions-button"><%= link_to("Predictions", predictions_url) %></li>
        <li id="new-prediction-button"><%= link_to("New Prediction", new_prediction_url) %></li>
        <li id="awaiting-judgment-button">
          <a href="<%= undetermined_url %>">Awaiting Judgment
          <span class="badge"><%= Prediction.due_for_judgment_count %></span></a>
        </li>
        <li id="tutorial-button"><a href="#">Tutorial</a></li>
      </ul>
      <form class="navbar-form navbar-left">
        <input type="text" class="form-control col-lg-8" placeholder="Search">
      </form>
      <% if signed_in? %>
      <ul class="nav navbar-nav navbar-right">
        <li id="dropdown-button" class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">Welcome,
            <%= current_user.username %><b class="caret"></b></a>
          <ul class="dropdown-menu">
            <li><%= link_to("Statistics", user_url(current_user)) %></li>
            <li><a href="#">Settings</a></li>
            <li class="divider"></li>
            <li><%= link_to("Sign Out", session_url, :method => :delete) %></li>
          </ul>
        </li>
      </ul>
      <% else %>
      <ul class="nav navbar-nav navbar-right">
        <li id="sign-in-button"><%= link_to("Sign In", new_session_url) %></li>
        <li id="sign-up-button"><%= link_to("Sign Up", new_user_url) %></li>
      </ul>
      <% end %>
    </div>
  </div>
</header>

<% if flash[:errors] %>
<div class="panel panel-danger">
  <div class="panel-heading">
    <h3 class="panel-title">Error</h3>
  </div>
  <div class="panel-body">
    <%= flash[:errors].join("<br>").html_safe if flash[:errors] %>
  </div>
</div>
<% end %>

<section class="container">

<%= yield %>

<footer>
  <div class="well well-sm">
    <div class="row">
      <div class="col-lg-12">
        <p> <strong>PredictionNote</strong> was made by <a href="http://jaysonvirissimo.github.io/" rel="nofollow">Jayson Virissimo</a>. Contact him at <a href="mailto:jayson.virissimo@asu.edu">jayson.virissimo@asu.edu</a>.</p>
        <p>The source code is released under the <a href="https://github.com/jaysonvirissimo/prediction-note/blob/master/LICENSE">BSD License</a> and can be found on <a href="https://github.com/jaysonvirissimo/prediction-note">GitHub</a>.</p>
      </div>
    </div>
  </div>
</footer>
</section>

<script type="text/javascript">
$(PredictionNote.initialize);
</script>
<h1>Backbone Test</h1>
<section class="container" id="content"></section>

</body>
</html>